name: Actualización Liga1

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"   # cada 5 minutos (puedes cambiar)

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script
        run: node update.js

      - name: Commit si cambió
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add liga1.m3u

          if git diff --cached --quiet; then
            echo "No hay cambios"
          else
            git commit -m "update link"
            git pull --rebase
            git push
          fi

